---
- name: checking installation
  hosts: openstack-vm
  become: yes
  vars:
    check: false
    monumental: ""
  tasks: 
    - name: checking openstack installation
      ansible.builtin.shell: "dpkg -l | grep openstack"
      register: check
      changed_when: false
      ignore_errors: true
    - name: Report if openstack is installed
      debug:
        msg: openstack is installed
      when: check.stdout
    - name: installing openstack
      debug:
        msg: openstack is not installed
      when: not check 


  
