---
- name: Gather information about a specific virtual machine
  hosts: openstack
  vars_files:
    - passwd.yml
  tasks:
    - name:
      community.vmware.vmware_vm_info:
        hostname: localhost.localdomain
        become: true
        password: "{{ openstack }}"
        vm_name: openstack-vm-test
      register: vm_info

    - name: Display gathered information
      debug:
        var: vm_info.virtual_machines
