---
- name: Add user 'stack' with root privs and install openstack via devstack
  hosts: openstack
  become: yes

  tasks:
    - name: Create stack user
      ansible.builtin.user:
        name: stack
        state: present
    - name: Allow 'stack' user to have passwordless sudo access
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: stack
        line: "stack ALL=(ALL) NOPASSWD: ALL"
