---
- name: openstack stuff
  hosts: openstack-vm
  tasks:
    - name: addrressing 
      openstack.cloud.address_scope:
        cloud: mycloud
        state: present
        name: my_adress_scope
    - name: addrressing
      openstack.cloud.address_scope:
        cloud: mycloud
        state: present
        ip_version: 6
        name: ipv6_address_scope
        project: myproj
    - name: addrressing 
      openstack.cloud.address_scope:
        cloud: mycloud
        state: absent
        name: my_adress_scope
