#!/bin/sh
NVM="openstack-vm"      
NVMDIR="openstack-vm"  
NVMOS="ubuntu-64"   
NVMSIZE="60g"          
VMMEMSIZE="8192"       
STATIC_IP="192.168.58.240"
NETMASK="255.255.255.0"
DNS_SERVER="8.8.8.8"
ISO_FILE="/vmfs/volumes/datastore1/install_server.iso"
MAC_ADDRESS="DE:AD:BE:A2:C1"
mkdir -p "/vmfs/volumes/datastore1/$NVMDIR"

vmkfstools -c "$NVMSIZE" -d thin "/vmfs/volumes/datastore1/$NVMDIR/$NVM.vmdk"

exec >"/vmfs/volumes/datastore1/$NVMDIR/$NVM.vmx"

cat <<EOF
.encoding="UTF-8"
config.version="8"
virtualHW.version="13"
nvram="openstack-vm.nvram"
pciBridge0.present="TRUE"
svga.present="TRUE"
pciBridge4.present="TRUE"
pciBridge4.virtualDev="pcieRootPort"
pciBridge4.functions="8"
pciBridge5.present="TRUE"
pciBridge5.virtualDev="pcieRootPort"
pciBridge5.functions="8"
pciBridge6.present="TRUE"
pciBridge6.virtualDev="pcieRootPort"
pciBridge6.functions="8"
pciBridge7.present="TRUE"
pciBridge7.virtualDev="pcieRootPort"
pciBridge7.functions="8"
vmci0.present="TRUE"
hpet0.present="TRUE"
floppy0.present="FALSE"
memSize="$VMMEMSIZE"
bios.bootRetry.delay="10"
sched.cpu.units="mhz"
sched.cpu.affinity="all"
sched.cpu.latencySensitivity="normal"
powerType.powerOff="default"
powerType.suspend="soft"
powerType.reset="default"
tools.upgrade.policy="manual"
scsi0.virtualDev="lsilogic"
scsi0.present="TRUE"
sata0.present="TRUE"
usb.present="TRUE"
ehci.present="TRUE"
svga.autodetect="TRUE"
scsi0:0.deviceType="scsi-hardDisk"
scsi0:0.fileName="/vmfs/volumes/datastore1/$NVMDIR/$NVM.vmdk"
sched.scsi0:0.shares="normal"
sched.scsi0:0.throughputCap="off"
scsi0:0.present="TRUE"
ethernet0.virtualDev="vmxnet3"
ethernet0.networkName="VM Network"
ethernet0.wakeOnPcktRcv="FALSE"
ethernet0.uptCompatibility="TRUE"
ethernet0.present="TRUE"
sata0:0.deviceType="cdrom-image"
sata0:0.fileName="$ISO_FILE"
sata0:0.present="TRUE"
displayName="$NVM"
guestOS="$NVMOS"
guestinfo.ipaddress="$STATIC_IP"
guestinfo.netmask="$NETMASK"
toolScripts.afterPowerOn="TRUE"
toolScripts.afterResume="TRUE"
toolScripts.beforeSuspend="TRUE"
toolScripts.beforePowerOff="TRUE"
tools.syncTime="FALSE"
sched.cpu.min="0"
sched.cpu.shares="normal"
sched.mem.min="0"
sched.mem.minSize="0"
sched.mem.shares="normal"
pciBridge0.pciSlotNumber="17"
pciBridge4.pciSlotNumber="21"
pciBridge5.pciSlotNumber="22"
pciBridge6.pciSlotNumber="23"
pciBridge7.pciSlotNumber="24"
scsi0.pciSlotNumber="16"
usb.pciSlotNumber="32"
ethernet0.pciSlotNumber="160"
ehci.pciSlotNumber="33"
vmci0.pciSlotNumber="34"
sata0.pciSlotNumber="35"
ethernet0.generatedAddressOffset ="0"
vmci0.id="-1805261126"
monitor.phys_bits_used="43"
vmotion.checkpointFBSize="4194304"
vmotion.checkpointSVGAPrimarySize="16777216"
cleanShutdown="TRUE"
softPowerOff="TRUE"
usb:1.speed="2"
usb:1.present="TRUE"
usb:1.deviceType="hub"
usb:1.port="1"
usb:1.parent="-1"
svga.guestBackedPrimaryAware="TRUE"
guestOS.detailed.data="architecture='X86' bitness='64' distroName='Ubuntu 22.04.2 LTS' distroVersion='22.04' familyName='Linux' kernelVersion='6.2.0-37-generic' prettyName='Ubuntu 22.04.2 LTS'"
usb:0.present="TRUE"
usb:0.deviceType="hid"
usb:0.port="0"
usb:0.parent="-1"
EOF
sleep 45
