---
- name: Create and provision VM on VMware Player and set up SSH pubkey authentication
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create VM and boot from ISO
      community.vmware.vmware_guest:
        hostname: localhost
        username: dinho
        password: ronaldinho gaucho 8010
        validate_certs: no
        name: openstack
        state: poweredon
        guest_id: ubuntu64Guest 
        num_cpus: 2
        memory_mb: 2048
        disk:
          - size_gb: 20
            type: thin
            datastore: openstack 
        cdrom:
          type: iso
          iso_path: /home/dinho/Downloads/ubuntu-22.04.3-desktop-amd64.iso
        networks:
          - name: bridged
            start_connected: yes
        wait_for_ip_address: yes
