---
- name: install openstack via devstack
  hosts: openstack-vm-test
  vars:
    ansible_become_pass: 'openstack' 
  tasks:
    - name: Clone openstack repo
      become: yes
      become_method: sudo
      become_user: stack
      ansible.builtin.shell:      
        cmd: 'git clone https://github.com/openstack/devstack.git /home/stack/devstack ; cd /home/stack/devstack ; git checkout stable/zed'
      ignore_errors: true
    - name: create openstack local.conf file
      ansible.builtin.copy:
        dest: /home/stack/devstack/local.conf
        src: /home/dinho/test/automation/local.conf
        mode: 0644      
    - name: Execute shell script
      become: yes
      become_method: sudo
      become_user: stack
      ignore_errors: true
      ansible.builtin.shell: 
        cmd: 'bash /home/stack/devstack/stack.sh'
    - name: Debug ansible_become_pass
      ansible.builtin.debug:
        msg: "ansible_become_pass is root"
    - name: Install python3-openstackclient
      become: yes
      become_method: sudo
      apt:
        name: python3-openstackclient
        state: present
    - name: Install python3-openstacksdk
      become: yes
      become_method: sudo
      ansible.builtin.shell:
        cmd: "pip install --upgrade 'openstacksdk>=1.0,<2.0'" 
