---
- name: Get all virtual machines
  hosts: openstack
  vars_files:
    - passwd.yml
  vars:
    ansible_become_pass: "{{ openstack }}"
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: no
  tasks:
    - name: Gather VM information
      vmware_vm_info:
        hostname: localhost
        vm_type: vm
      register: vm_info
    - name: Display virtual machines
      debug:
        var: vm_info.virtual_machines
