---
- name: Set IP address for openstack-vm on ESXi host
  hosts: openstack
  gather_facts: no
  vars_files:
    - passwd.yml
  vars:
    esxi_username: "root"
    esxi_password: "{{ openstack }}"
    vm_name: "openstack-vm"
    new_ip_address: "192.168.58.240"
    subnet_mask: "255.255.255.0"
    dns_servers:
      - "8.8.8.8"

  tasks:
    - name: Set IP address for openstack-vm
      community.vmware.vmware_vm_vmotion:
        hostname: "openstack"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: no
        name: "{{ vm_name }}"
        ip_settings:
          ip: "{{ new_ip_address }}"
          subnet_mask: "{{ subnet_mask }}"
          dns_servers: "{{ dns_servers }}"
        state: present

      
      
