---
- name: launch openstack virtual machine for the first time
  hosts: openstack
  become: yes
  vars_files:
    - passwd.yml
  vars:
    ssh_username: root
    ansible_ssh_private_key_file: /home/dinho/.ssh/id_rsa.pub
    ansible_become_pass: "{{ openstack }}"
  tasks:
    - name: launch VM ...
      ansible.builtin.shell:
        cmd: "a=`vim-cmd vmsvc/getallvms | grep openstack-vm | cut -d " " -f 1` ; vim-cmd vmsvc/power.on $a ;" 
