#---
#- name: python version verification
#  hosts: openstack
#  gather_facts: yes
#  tasks: 
#    - name: Display python version if installed
#      debug: 
#        var: ansible_python_version
#    - name: Display Python interpreter path
#      debug:
#        var: ansible_facts['ansible_python']['executable']
---
- name: Find Python interpreter on the target machine
  hosts: openstack
  gather_facts: no  
  vars:
    python_interpreter_path: "/usr/bin/python"
  tasks:
    - name: Display Python interpreter path
      debug:
        msg: "Python interpreter path: {{ python_interpreter_path }}"
