---
- name: Connect to remote machine via SSH with a specific username and password
  hosts: openstack
  gather_facts: no

  vars:
    ssh_username: cloud-admin
    ansible_ssh_private_key_file: /home/dinho/.ssh/id_rsa.pub
    ansible_become_pass: openstack

  tasks:
    - name: Check connectivity
      ansible.builtin.ping:
      delegate_to: localhost
      become: no
    - name: Run command
      ansible.builtin.shell:
        cmd: pwd
      register: command_output

    - name: Display command output
      ansible.builtin.debug:
        var: command_output.stdout
    - name: Create stack user
      become: yes
      become_method: sudo
      remote_user: cloud_admin
      ansible.builtin.user:
        name: stack
        state: present
    - name: Allow 'stack' user to have passwordless sudo access
      become: yes
      become_method: sudo
      remote_user: cloud_admin
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: stack
        line: "cloud-admin ALL=(ALL) NOPASSWD: ALL"

