---
- name: Connect to remote machine via SSH with a specific username and password
  hosts: openstack
  gather_facts: no
  vars_files:
    - passwd.yml
  vars:
    ssh_username: root
    ansible_ssh_private_key_file: /home/dinho/.ssh/id_rsa.pub
    ansible_become_pass: "{{ openstack }}"

  tasks:
    - name: Check connectivity
      ansible.builtin.ping:
      delegate_to: localhost
      become: no
    - name: Run command
      ansible.builtin.shell:
        cmd: pwd
      register: command_output

    - name: Display command output
      ansible.builtin.debug:
        var: command_output.stdout
    - name: Create stack user
      become: yes
      become_method: sudo
      remote_user: root
      ansible.builtin.user:
        name: stack
        state: present
    - name: Allow 'stack' user to have passwordless sudo access
      become: yes
      become_method: sudo
      remote_user: root
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: stack
        line: "stack ALL=(ALL) NOPASSWD: ALL"

