---
- name: List OpenStack Security Groups
  hosts: openstack-vm-test
  become: true
  become_method: sudo
  become_user: stack
  tasks:
    - name: Gather OpenStack security groups
      ansible.builtin.shell:
        cmd: 'openstack --os-username=admin --os-password=secret --os-project-name=demo --os-auth-url=http://10.10.17.245/identity --os-project-domain-name=default --os-user-domain-name=default security group list'
      register: os_security_groups

    - name: Display security groups
      debug:
        msg: "{{ os_security_groups }}"

